# Generated by Django 5.0.2 on 2024-02-27 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Movie Title')),
                ('img', models.ImageField(default='', upload_to='movie_covers', verbose_name='Movie Cover Image')),
                ('tickets', models.PositiveIntegerField(verbose_name='Available Tickets')),
                ('description', models.TextField(verbose_name='Brief Description')),
                ('theatre', models.CharField(max_length=100, verbose_name='Related Theatre')),
                ('tickets_available', models.BooleanField(default=True, verbose_name='Tickets Available')),
                ('date_time', models.DateTimeField(verbose_name='Scheduled On')),
            ],
        ),
    ]
