# Generated by Django 5.0.2 on 2024-02-27 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='booked_tickets',
            field=models.IntegerField(default=0, verbose_name='Booked Tickets'),
        ),
    ]
