# Generated by Django 5.0.2 on 2024-02-28 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_movie_booked_tickets'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='price',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
