# Generated by Django 5.0.2 on 2024-02-28 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_movie_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='Seat Name/Title')),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='reserved_seats',
            field=models.ManyToManyField(null=True, to='api.seat', verbose_name='Reserved Seats'),
        ),
    ]
