# Generated by Django 5.0.2 on 2024-02-29 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_seat_movie_reserved_seats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='theatre',
        ),
    ]
